### ISSUE TITLE
Advanced stuff not working

### ISSUE THREAD

**Issue by mkddostro** [monkeysuffrage/advanced_html_dom#24]
```
$tables = $html->search('table:not(.bg-secondary)');
foreach($tables AS $table){
    echo $table->class.'<br>';
}
```

results in
> [...]
> container
> container bg-secondary
> container
> [...]

Guess expecting the code to ignore the tables having the class .bg-secondary was a fallacy.

Switching to ":has" also returns two table elements (without actually echoing "container bg-secondary" but only "container") although the class bg-secondary is definitely only used on one element in the source.

btw, putting so many more possibilities into simple html dom and calling it advanced but not giving any actual examples apart from "it's like simple but with added jquery selectors and functions" doesn't help and won't get this much attention. But people told you already and you didn't mind.

This class looks like work in progress and you shouldn't have put it all over the net like stackoverflow when it's not ready.

**Comment by monkeysuffrage** [comment]
:not(.xxx) will ignore elements with a .xxx descendent. I think that behavior is consistent with Nokogiri though maybe not jquery.

You're welcome to your opinions and if you prefer simple html dom please continue using it. I personally find simple html dom unusable and that's why I had to make this.
